### ISSUE TITLE
What is the difference between number and number of things?

### ISSUE THREAD

**Issue by rjyounes** [semanticarts/gistReferenceData#27]
We have two UnitGroups and Aspects for number and number of things. How do they differ? Can they be combined?

**Comment by philblackwood** [comment]
@rjyounes there are two options for dealing with a case like "number of cartons". That could be thought of as an aspect or as a unit. Since in general the units are very standard while the aspects tend to be very enterprise-specific, I would lean toward making these aspects and using gistd:_UnitOfMeasure_count or gistd:_UnitOfMeasure_unitless for the unit.

Do you have a preference?

**Comment by rjyounes** [comment]
I find it more natural to think of these as units rather than aspects, and my client needs a consistent way to compose labels from numeric value + unit of measure; for both reasons, I prefer modeling them as units. However, I understand there's a concern about proliferating such units, since there are so many terms for containers or other ways that things are packaged - box, bag, sack, case, carton, tube, sheet, strip, etc., etc. So I don't mind if they have to be defined in the client namespace rather than in the reference data.

**Comment by rjyounes** [comment]
Question answered, closing.
